### ISSUE TITLE
ERR_CONNECTION_REFUSED for websocket requests

### ISSUE THREAD

**Issue by enigmartin** [persys-ai/persys-server#1]
I have tried to set up persys with both server and electron app on the same machine as well as with the server on a remote machine. Both ways, I'm running into an issue where, even after opening ports, double checking firewall, etc., the front end reports this in the console when trying to send a message via the chat interface:

`WebSocket connection to 'ws://localhost:9000/chat/peerjs?key=peerjs&id=***&token=***&version=1.5.4' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

Have tried monkeying around with the peerServer config on the server side as well as the chat interface file, but have not found a way to get the interface.min recompiled nor a way around this error.

I've set up the `p.json` file in the root of the data directory and login works fine, the `t.json` is showing tokens as expected.

**Comment by space0blaster** [comment]
is chat.js running? check with `pm2 ps`
what do you get when you run `curl http://localhost:9000/chat`

**Comment by space0blaster** [comment]
Dockerfile has been added fyi if you'd like to go that route now.

**Comment by enigmartin** [comment]
I went the Docker route, and that resolved the failed connection issue. Now I'm having a different problem where all I'm getting back from the server is the heartbeat via websocket after initiating a conversation. Any further messages in the same conversation result in this from the peerjs endpoint: `{"type":"ID-TAKEN","payload":{"msg":"ID is taken"}}`. No errors appear in the persys-server log. This appears from PM just before the `PERSYS is running` line:

```
┌────┬──────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐

│ id │ name     │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │

├────┼──────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤

│ 1  │ chat     │ default     │ N/A     │ fork    │ 55       │ 0s     │ 0    │ online    │ 100%     │ 67.6mb   │ root     │ disabled │

│ 2  │ rag      │ default     │ N/A     │ fork    │ 77       │ 0s     │ 0    │ online    │ 0%       │ 9.1mb    │ root     │ disabled │

│ 0  │ stats    │ default     │ N/A     │ fork    │ 29       │ 0s     │ 0    │ online    │ 0%       │ 72.0mb   │ root     │ disabled │

└────┴──────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘

[PM2] Saving current process list...
``` 

Edit:
This is what I get when I got to localhost:9000/chat:
`{"name":"PeerJS Server","description":"A server side element to broker connections between PeerJS clients.","website":"https://peerjs.com/"}`

**Comment by space0blaster** [comment]
pushing an update for log location, it'll be under `baseDir/logs`
trying to replicate your issue now

**Comment by space0blaster** [comment]
pushed the log output patch
use `tail -f {your-base-dir}/logs/chat-err.log` to stream logs while initiating a chat session
if you get nothing there, also print your main server logs by `tail -f {your-base-dir}/logs/server-err.log`

are rag.js and stats.js also giving you the same error? (use the latest push, there was a bug for rag.js on previous commit)

**Comment by enigmartin** [comment]
Figured it out. I wasn't getting any errors that pm2 wasn't running correctly (when not using Docker). Didn't realize that pm2 needed to run globally. Any reason that isn't included as a project dependency and is used globally?

**Comment by space0blaster** [comment]
Ah! It should be global. Glad it's working, I'll create an updated install.sh for non-docker installs. Let me know if you run into other issues. Reviewing the dotenv pull, looks great.
